version: "2"
services:
  node: 
    restart: always
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3333"
    command: "npm run start-prod"
